- name: Using Ansible Facts
  hosts: workers

  tasks:
    - name: create a file
      lineinfile:
        path: /home/ansible/hostname
        create: yes
        line: "{{ansible_hostname}}" # this is a standard variable defined in ansible facts

    - name: access magic variable
      lineinfile:
        path: /home/ansible/hostname
        line: "{{hostvars['localhost']['ansible_default_ipv4']['address']}}"

