apiVersion: v1
kind: Pod
metadata:
  name: volume-pod
  namespace: demo
spec:
  restartPolicy: Never
  containers:
  - name: busybox
    image: busybox
    command: ['sh', '-c', 'echo Success! > /output/success.txt']
    volumeMounts:
    - name: my-volume
      mountPath: /output
  volumes:
  - name: my-volume
    # store the data on the specified directory of host k8s node
    hostPath:
      path: /var/data
  