apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: my-pvc
  namespace: demo
spec:
  storageClassName: localdisk
  accessModes:
   - ReadWriteOnce
  resources:
    requests:
     storage: 100Mi