apiVersion: v1
kind: Pod
metadata:
  name: pv-pod
  namespace: demo
spec:
  restartPolicy: Never
  containers:
    - name: busybox
      image: busybox
      command: ['sh', '-c', 'echo Writing to the pv > /output/notes.txt']
      volumeMounts:
        - name: pv-storage
          mountPath: /output
  volumes:
    - name: pv-storage
      persistentVolumeClaim:
       claimName: my-pvc