- hosts: workers
  become: yes
  tasks:
    - name: install packets
      apt:
        name: "{{ item }}"
        state: latest
        update_cache: yes
      loop:
       - tree
       - nmap
       - bind9
      