- hosts: all
  become: yes
  tasks:
  - name: Add the user 'johnd' with a specific uid and a primary group of 'sudo'
    ansible.builtin.user:
      name: johnd
      password: '$6$akQIADBFaU8$bUmF2E1mHDRD8BX7Q75lxI1LChwHSNvrbT8MvjcY5jHH69Zbu2Uk3UMQUTQAqREw4n/4MMRx7MBMRyLfJP0kE/' #copy from mkpasswd output
      comment: John Doe
      shell: /bin/bash
      uid: 1040
      group: sudo